name: "Nix preparation"
description: "Prepares the nix shell for the running CI"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
