[package]
name = "flakeshot"
version = "0.1.0"
edition = "2021"
description = "A screenshot tool for wayland and x11 written in rust."
repository = "https://github.com/eneoli/flakeshot"
authors = ["eneoli", "TornaxO7"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
arboard = "3.2"
clap = { version = "4.4", features = ["derive", "cargo"] }
image = "0.24"
tokio = { version = "1.34", features = ["full"] }
