---
name: Bug Report
description: File a bug report to help improving flakeshot!
title: "Bug Report"
labels:
  - bug
projects:
  - eneoli/flakeshot
assignees: []
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: A bug happened!
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How can we reproduce the bug?
      description: A small HowTo trigger the issue.
      placeholder: 1. Run flakeshot in tray mode \n 2. ...
    validations:
      required: true
  - type: dropdown
    id: display-protocol
    attributes:
      label: Display Protocol
      description: Do you use Wayland or X11?
      options:
        - Wayland
        - X11
      default: 0
    validations:
      required: true
  - type: input
    id: distro
    attributes:
      label: Which Linux Distro do you use?
      placeholder: I use Arch btw.
  - type: textarea
    id: monitors
    attributes:
      label: How many monitors do you have and how are they orientated?
      placeholder: I have two monitors both orientateed side to side in landscape.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: shell
