name: CI

# Use our Nix Flake Environment for steps
defaults:
  run:
    shell: nix develop --command bash {0}

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v22
        with:
         nix_path: nixpkgs=channel:nixos-unstable
      - name: Check formatting
        run: cargo fmt --check --verbose
      - name: Check best practices (Clippy)
        run: cargo clippy --verbose
      - name: Check for build errors
        run: cargo check --verbose
      - name: Running tests
        run: cargo test --verbose